print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = float(input("How much tip would you like to give? "))
people = float(input("How many people to split the bill? "))
total = round(((bill/people) + (bill/people)*0.01*tip),2)
print(f"Each person should pay: {total}")
